### ISSUE TITLE
Is there a safe/recommended way to upgrade yt-dlp before xklb has quite caught up? 

### ISSUE THREAD

**Issue by holta** [chapmanjacobd/library#20]
Or is that unwise?

(Many thanks @chapmanjacobd for your suggestions and/or recommendation here!)

Related:

- https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16
- https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.14
- e.g. xklb currently includes yt-dlp 2023.10.13: https://github.com/chapmanjacobd/library/blob/e96edb0a80337bffa316562e719765aeeca55131/pdm.lock#L2533-L2549

**Comment by chapmanjacobd** [comment]
hey Adam,

You should be fine doing:

```
pip install --upgrade xklb
```

And then months later:

```
pip install --upgrade yt-dlp
```

Things should just work. Even though `library` and `yt-dlp` depend on having a common interface in one or two places--it is unlikely to break. If things break, open a specific issue for it and I'll try to get things back on track ASAP :-)

Personally, I update yt-dlp each week as a cron-job but if there is a platform change then sometimes I will do the above `pip install --upgrade yt-dlp`. 

You can also try `yt-dlp --update-to master` and I think it should be fine assuming it uses the same python environment that xklb is installed in (I haven't tried this yet).

The pdm.lock file is mostly aspirational. So don't take it too seriously :)
