### ISSUE TITLE
Captions/Subtitle Search feature is broken

### ISSUE THREAD

**Issue by deldesir** [chapmanjacobd/library#39]
**Describe the bug**
Searching captions/subtitles no longer works
Error:
`sqlite3.OperationalError: no such column: m.time_deleted`

**Expected behavior**
Xklb should return the captions found and the titles of the video(s) related to them

**To Reproduce**
```
root@box:/usr/local/calibre-web-py3# lb search /library/calibre-web/xklb-metadata.db people
Traceback (most recent call last):
  File "/usr/local/bin/lb", line 8, in <module>
    sys.exit(library())
             ^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/xklb/lb.py", line 304, in library
    return args.func()
           ^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/xklb/lb.py", line 250, in import_func
    return getattr(module, function_name)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/xklb/mediadb/search.py", line 100, in search
    captions = list(args.db.query(query, bindings))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/sqlite_utils/db.py", line 503, in query
    cursor = self.execute(sql, params or tuple())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/xklb/lib/python3.12/site-packages/sqlite_utils/db.py", line 521, in execute
    return self.conn.execute(sql, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: m.time_deleted
```
 - library --version 2.8.0.49

**Comment by holta** [comment]
Thanks @deldesir for catching this!

(As this'll be very important among students/teachers searching their offline video collections...)

- PR iiab/calibre-web#140
- PR iiab/calibre-web#152

**Comment by chapmanjacobd** [comment]
It would be interesting to know how the xklb-metadata.db was created so that I can fix other? bugs, if any. The problem with making _all_ the schema/queries column-optional is that silent data bugs will exponentiate...

**Comment by holta** [comment]
> interesting to know how the xklb-metadata.db was created

@deldesir can you link to precise code, showing were xklb-metadata.db is created?

Thanks if you can please.

**Comment by deldesir** [comment]
xklb-metadata.db is created by https://github.com/iiab/calibre-web/blob/916963a17cf5074e402e9c49ec608abf43809f32/scripts/lb-wrapper#L56

**Comment by holta** [comment]
> okay it should be working in 2.8.050

Priceless:

@deldesir and I have decided to focus on getting search (across all local books/videos/etc) working as rigorously/reliably as possible in coming days and weeks[*].  So hopefully he can respond to your (@chapmanjacobd) TDD-oriented suggestions very soon, as this all points precisely to what grassroots communities need _(meaningful local learning, not info-bloat!)_ 💯

[*] CAVEAT: Bogus captions and extremely poor-quality transcriptions are something we all have to live with for now, all too often, and so be it.  (Let us hope that extremely low-quality transcriptions / captions / sub-titles finally start becoming increasingly more sane in 2025 ;-)

**Comment by deldesir** [comment]
Thank you for the quick fix @chapmanjacobd

> It looks like this could also benefit from having one or two simple tests

I appreciate the suggestion. I'm not good at writing tests [yet], I'll do my best to learn and get this done.
