### ISSUE TITLE
error: invalid choice: 'media-check'

### ISSUE THREAD

**Issue by manderso7** [chapmanjacobd/library#42]
**Describe the bug**
when running ```/home/manderso/.local/bin/library media-check --full-scan unraid-media/movies/american\ psycho/American\ Psycho\ \(2000\).mkv``` I receive ```lb: error: invalid choice: 'media-check' (choose from...```

**Expected behavior**
the media-check plugin to be found and get started on it's task

**To Reproduce**
```library media-check --full-scan <filename>```
 - library --version
2.2.135

**Comment by chapmanjacobd** [comment]
I'm pretty sure the media-check option wasn't added until 2.8 or so. you'll need to update xklb

    pip install --upgrade xklb
